version: '3.9'
services:
  app:
    container_name: "app2"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app